import AdzenerLogo from "../assets/AdzenerLogo.svg";
import SubmitButton from "../components/Buttons/SubmitButton";
import { Plus, Minus } from 'lucide-react';
import { useState } from "react";
import Footer from "../components/Footer";

import Dashboard from "/src/assets/webimages/Dashboard.png";
import PromptContainer from "/src/assets/webimages/promtContainer.png";
import ReasoningMobile from "/src/assets/webimages/ReasoningMobile.png";
import campaignCreation2 from "/src/assets/webimages/campaignCreation2.png";
import createContent1 from "/src/assets/webimages/createContent1.png";
import createdPosts from "/src/assets/webimages/createdPosts1.png";
import PromptDetails1 from "/src/assets/webimages/promptDetails1.png";
import Aboutus from "/src/assets/webimages/Aboutus.svg";

export default function Home() {
    const faqs = [
    {
        question: "1. What exactly does Adzener do?",
        answer: "Adzener helps generate and optimize AI-powered marketing campaigns tailored to your goals and audience.",
    },
    {
        question: "2. Who is Adzener built for?",
        answer: "It’s designed for marketers, startups, and businesses looking to automate campaign creation and optimization.",
    },
    {
        question: "3. Can I customize the campaigns generated by Adzener?",
        answer: "Yes, all campaigns are editable before publishing—captions, visuals, and scheduling are fully customizable.",
    },
    {
        question: "4. Does Adzener integrate with social platforms?",
        answer: "Absolutely! Adzener supports direct publishing to platforms like Facebook, Instagram, LinkedIn, and TikTok.",
    },
    {
        question: "6. How does Adzener use AI to optimize content?",
        answer: "Adzener uses AI to craft high-converting copy, choose visuals, and schedule posts based on audience behavior.",
    },
    ];

    const [openIndex, setOpenIndex] = useState(null);

    const toggle = (index) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <div className="min-h-screen bg-gradient-to-br flex items-center flex-col" style={{ backgroundColor: "#F5F3F8" }}>
            <div className="w-full max-w-6xl flex rounded-2xl overflow-hidden flex-col">
                <div className="w-full flex pl-28 pt-11">
                    <img src={AdzenerLogo} alt="Adzener Logo" style={{ maxWidth: "100%" }} />  
                </div>
                <div className="w-full flex flex-col items-center mt-28">
                    <div className="rounded-3xl" style={{ maxWidth: "500px", textAlign: "center", fontSize:"14px" , padding: "10px 13px 10px 13px", color: "#6C975E",boxShadow: "0px 0px 10px 2px rgba(108,151,94,0.72)" }}>
                        <p>
                            Smart marketing starts here. Adzener Beta is now live! Request a demo
                        </p>
                    </div>
                    <p className="w-full text-5xl font-extrabold mt-10 text-center">
                        Revolutionize Your
                    </p>
                    <p className="w-full text-5xl font-extrabold mt-6 text-center">
                        Marketing with AI 
                    </p>
                    <p className="text-center w-full" style={{ maxWidth: "600px", fontSize: "16px", color: "#6C975E", marginTop: "20px" }}>
                        From strategy to execution,  launch personalized campaigns in minutes. Empower your team with AI-driven content, insights, and automation that scale.
                    </p>
                    <SubmitButton
                        text="Request a Demo"
                        style={{ marginTop: "30px", maxWidth: "200px" , borderRadius: "10px" }}
                        onClick={() => window.location.href = "https://calendly.com/adzener/30min"}
                    ></SubmitButton>
                </div>
                <div className="pt-20 pl-36 pr-36 flex justify-center items-center flex-row gap-8 mb-10">
                    <div className="hidden lg:flex lg:w-1/2 items-center justify-center flex-col">
                        <p className="text-left text-3xl font-bold mb-8">Smarter Campaigns, Seamless Workflows</p>
                        <p style={{color:"#282A3ACC"}} className="mb-10">
                            Adzener is an intelligent platform that empowers small teams and marketing professionals to build, optimize, and manage full-scale marketing campaigns using AI agents. Say goodbye to disconnected tools and manual workflows, Adzener brings everything you need into one place.
                        </p>
                    </div>
                    <div
                        className="hidden lg:flex lg:w-1/2 items-center justify-center p-12"
                        style={{ position: 'relative', width: '350px', height: '300px' }} // adjust as needed
                        >
                        <img
                            src={Dashboard}
                            alt=""
                            style={{
                            position: 'absolute',
                            bottom: '50px',
                            left: '55%',
                            transform: 'translateX(-50%)',
                            width: '85%',
                            zIndex: 0,
                            boxShadow: "0px 0px 10px 2px rgba(108,151,94,0.72)"
                            }}
                        />
                        <img
                            src={ReasoningMobile}
                            alt=""
                            style={{
                            position: 'absolute',
                            bottom: '10px',
                            left: '0',
                            width: '20%',
                            zIndex: 1,
                            boxShadow: "0px 0px 10px 2px rgba(108,151,94,0.72)"
                            }}
                        />
                        <img
                            src={PromptContainer}
                            alt=""
                            style={{
                            position: 'absolute',
                            bottom: '20px',
                            right: '0',
                            transform: 'translateX(20%) scale(0.95)',
                            width: '55%',
                            zIndex: 1,
                            boxShadow: "0px 0px 10px 2px rgba(108,151,94,0.72)"
                            }}
                        />
                    </div>
                </div>
                <div className="flex justify-center items-center flex-col p-4">
                    <p className="text-left text-3xl font-bold mb-8">Why Marketers Love Adzener</p>
                        <div className="flex flex-wrap justify-center gap-6">
                            <div className="flex flex-row gap-6 justify-center">
                                <div className="flex flex-col w-[45%] rounded-2xl shadow p-6">
                                    <h3 className="text-xl font-semibold mb-2">Smart Campaign Design</h3>
                                    <p className="text-sm text-gray-600 mb-4">
                                    Generate AI-tailored campaigns based on your goals, audience, and trends—
                                    no creative block, just strategy that sticks.
                                    </p>
                                    <img src={createdPosts} alt="Campaign Design" className="rounded-xl" />
                                </div>

                            <div className="flex flex-col w-[30%] rounded-2xl shadow p-6">
                                <h3 className="text-xl font-semibold mb-2">AI-Powered Content Optimization</h3>
                                <p className="text-sm text-gray-600 mb-4">
                                Produce high-performing copy instantly. From posts to CTAs, everything is optimized for engagement and conversion.
                                </p>
                                <img src={PromptDetails1} alt="Content Optimization" className="rounded-xl" />
                            </div>
                        </div>
                        

                        <div className="flex flex-wrap justify-center gap-6">
                            <div className="flex flex-col w-[30%]  rounded-2xl shadow p-6">
                                <h3 className="text-xl font-semibold mb-2">Real-Time Analytics</h3>
                                <p className="text-sm text-gray-600 mb-4">
                                Launch, track, and let Adzener improve your campaign performance while you sleep.
                                </p>
                                <img src={campaignCreation2} alt="Analytics" className="rounded-xl" />
                            </div>

                            {/* Block 4 - Quick Post Creation & Scheduling */}
                            <div className="flex flex-col w-[45%] rounded-2xl shadow p-6">
                                <h3 className="text-xl font-semibold mb-2">Quick Post Creation & Scheduling</h3>
                                <p className="text-sm text-gray-600 mb-4">
                                Create beautiful, platform-ready posts in minutes with AI-generated visuals and captions.
                                </p>
                                <img src={createContent1} alt="Post Creation" className="rounded-xl" />
                            </div>
                        </div>
                    </div>
                </div>
                <div className="pt-10 pl-36 pr-36 flex justify-center items-center flex-row">
                    <div className="hidden lg:flex lg:w-1/2 items-center justify-center p-12 flex-col">
                        <p className="text-left text-3xl font-bold mb-8">About Us</p>
                        <p style={{color:"#282A3ACC"}} className="mb-10">
                           At Adzener, we're a team of curious builders, marketers, and designers who've lived through the chaos of disconnected tools, blank content calendars, and sleepless campaign launches. We believe great marketing shouldn't be limited by time, tools, or team size.With Adzener, we're not just building a product — we're building the future of how campaigns are created.
                        </p>
                    </div>
                    <div className="hidden lg:flex lg:w-1/2 items-center justify-center p-12">
                        <img
                            src={Aboutus}
                            alt="About Us"
                            style={{
                                width: '150%',
                                height: 'auto',
                            }}
                        />
                    </div>
                </div>
                <div className="flex justify-center items-center flex-column">
                    <div className="flex items-center flex-col">
                        <p className="text-center text-3xl font-bold mb-8">FAQ</p>
                        <div className="w-full mx-auto space-y-3 px-4">
                        {faqs.map((item, index) => (
                            <div
                            key={index}
                            className="rounded-xl border border-gray-200 py-4 "
                            style={{width: "800px"}}
                            >
                            <button
                                onClick={() => toggle(index)}
                                className="flex justify-between items-center w-full text-left font-medium text-gray-800 px-4"
                            >
                                <span>{item.question}</span>
                                {openIndex === index ? <Minus size={18} /> : <Plus size={18} />}
                            </button>
                            {openIndex === index && (
                                <div className="mt-3 text-sm text-gray-600 px-4">{item.answer}</div>
                            )}
                            </div>
                        ))}
                        </div>
                    </div>
                </div>
                <div className="mt-20 ml-36 mr-36 flex justify-center items-center flex-column">
                    <div className="w-full flex items-center flex-col p-10" style={{ backgroundColor: "#6C975E", color: "white", borderRadius: "30px"}}>
                        <p className="text-center text-3xl font-bold mb-8 max-w-96 mt-10">Ready to Launch Smarter Campaigns?</p>
                        <p className="text-center max-w-96">Let Adzener be your edge in a crowded marketing world,  faster workflows, better content, and AI that truly understands your goals.</p>
                         <SubmitButton
                            text="Request a Demo"
                            style={{ marginTop: "30px", maxWidth: "200px" , borderRadius: "10px", backgroundColor: "white", color: "#6C975E" , fontWeight: "bold"  }}
                            onClick={() => window.location.href = "https://calendly.com/adzener/30min"}
                        ></SubmitButton>
                    </div>
                </div>
            </div>
            <div className="w-full flex justify-center items-center mt-10 mb-10">
                <Footer />
            </div>
        </div>
    );
}

